package dns_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/lexfrei/pingora-gateway-controller/internal/dns"
)

func TestDetectClusterDomain(t *testing.T) {
	t.Parallel()

	// This test verifies the public API works.
	// The actual detection depends on /etc/resolv.conf which varies by environment.
	// We just verify it doesn't panic and returns valid types.
	domain, found := dns.DetectClusterDomain()
	t.Logf("DetectClusterDomain() = %q, found = %v", domain, found)

	// If found, domain should not be empty
	if found && domain == "" {
		t.Error("DetectClusterDomain() found=true but domain is empty")
	}
}

func TestDetectClusterDomainFromFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		content    string
		expected   string
		shouldFind bool
	}{
		{
			name: "standard resolv.conf",
			content: `# Generated by NetworkManager
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
`,
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name: "custom cluster domain",
			content: `nameserver 10.0.0.10
search myapp.svc.custom.domain svc.custom.domain custom.domain
options ndots:2
`,
			expected:   "custom.domain",
			shouldFind: true,
		},
		{
			name: "resolv.conf with comments",
			content: `# This is a comment
; Another comment style
nameserver 8.8.8.8

search test.svc.k8s.internal svc.k8s.internal k8s.internal
`,
			expected:   "k8s.internal",
			shouldFind: true,
		},
		{
			name: "no search directive",
			content: `nameserver 8.8.8.8
nameserver 8.8.4.4
`,
			expected:   "",
			shouldFind: false,
		},
		{
			name: "search without svc domain",
			content: `nameserver 10.0.0.1
search example.com corp.local
`,
			expected:   "",
			shouldFind: false,
		},
		{
			name:       "empty file",
			content:    "",
			expected:   "",
			shouldFind: false,
		},
		{
			name: "multiple search lines takes first match",
			content: `nameserver 10.96.0.10
search first.svc.domain1.local svc.domain1.local
search second.svc.domain2.local svc.domain2.local
`,
			expected:   "domain1.local",
			shouldFind: true,
		},
	}

	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			// Create temp file with test content
			tmpDir := t.TempDir()
			tmpFile := filepath.Join(tmpDir, "resolv.conf")

			err := os.WriteFile(tmpFile, []byte(testCase.content), 0o600)
			if err != nil {
				t.Fatalf("failed to write temp file: %v", err)
			}

			result, found := dns.DetectClusterDomainFromFile(tmpFile)

			if found != testCase.shouldFind {
				t.Errorf("DetectClusterDomainFromFile() found = %v, want %v", found, testCase.shouldFind)
			}

			if result != testCase.expected {
				t.Errorf("DetectClusterDomainFromFile() = %q, want %q", result, testCase.expected)
			}
		})
	}
}

func TestDetectClusterDomainFromFile_NonExistent(t *testing.T) {
	t.Parallel()

	result, found := dns.DetectClusterDomainFromFile("/nonexistent/path/resolv.conf")

	if found {
		t.Error("DetectClusterDomainFromFile() should return false for non-existent file")
	}

	if result != "" {
		t.Errorf("DetectClusterDomainFromFile() = %q, want empty string", result)
	}
}
